services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - transcendance-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - transcendance.env

  backend:
    build: ./backend
    command: daphne -b 0.0.0.0 -p 8000 Transcendance.asgi:application  # Utiliser Daphne ici
    networks:
      - transcendance-network
    environment:
      - DJANGO_SETTINGS_MODULE=Transcendance.settings
      - MEDIA_URL=http://localhost:8000/media/
      - FRONTEND_URL=http://localhost:5500
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
      - media_volume:/app/media
    ports:
      - 8000:8000
    env_file:
      - transcendance.env
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - transcendance-network

  frontend:
    build: ./frontend
    image: nginx:alpine
    networks:
      - transcendance-network
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/media:/usr/share/nginx/html/media:ro
    ports:
      - "5500:5500"  
    depends_on:
      - backend

networks:
  transcendance-network:
    driver: bridge

volumes: 
  postgres_data:
  media_volume: