# Generated by Django 5.1.2 on 2024-10-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('win', models.IntegerField(default=0)),
                ('loose', models.IntegerField(default=0)),
                ('winrate', models.FloatField(default=0.0)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
