# Generated by Django 5.1.2 on 2024-10-24 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_x', models.IntegerField(default=400)),
                ('ball_y', models.IntegerField(default=300)),
                ('ball_speed_x', models.IntegerField(default=5)),
                ('ball_speed_y', models.IntegerField(default=5)),
                ('left_paddle_y', models.IntegerField(default=250)),
                ('right_paddle_y', models.IntegerField(default=250)),
                ('left_score', models.IntegerField(default=0)),
                ('right_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('player_left', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_left', to=settings.AUTH_USER_MODEL)),
                ('player_right', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_right', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
